/**
 * scripts/lib/scaffold-frontend/routes-nav.mjs — the route + nav appenders (step c) and the
 * route-path helpers the page emitters share.
 *
 *   routeSegments  a route path → its Next app-router folder segments (used everywhere a page
 *                  dir is computed).
 *   pathWords      tokenize a route path into lowercase words.
 *   routeKey       UPPER_SNAKE route key (explicit route.key, else entity/path).
 *   appendRoute    idempotently insert an APP_ROUTES entry into src/app-routes.ts.
 *   appendNavItem  idempotently insert a NavItem into src/lib/navigation/sidebar-config.ts.
 *
 * Both appenders are idempotent (skip when the path/href is already declared) and tab-indented
 * to match the base template; a missing/odd-shaped anchor file WARNs (never half-patches).
 */

import * as fs from 'fs';
import * as path from 'path';
import { words, pluralizeWords } from '../inflect.mjs';
import { write, skip, rel, escapeRegex } from './writers.mjs';

/**
 * The Next.js app-router folder segments for a route path. Each URL segment
 * becomes one directory; a dynamic `[id]` segment is preserved verbatim. `/` (the
 * root) maps to no extra segments (the app/ dir itself).
 */
export function routeSegments(p) {
  return String(p || '/')
    .replace(/^\//, '')
    .split('/')
    .filter(Boolean);
}

/** Tokenize a route path into lowercase words (also splitting on `/`). */
export function pathWords(p) {
  return String(p || '')
    .replace(/^\//, '')
    .split('/')
    .flatMap((seg) => words(seg))
    .filter(Boolean);
}

/**
 * Route key (UPPER_SNAKE) from an explicit `route.key`, else the entity or path
 * (e.g. blog-post → BLOG_POSTS). The explicit key lets the flow-mount step give its
 * /org/<sub> routes keys that do NOT collide with the base template's existing
 * APP_ROUTES keys (the template already declares ORG_MEMBERS / ORG_SETTINGS /
 * ORG_INVITES for its own /orgs/[orgId]/… routes; a derived /org/members key would
 * duplicate them and break the `as const` object).
 */
export function routeKey(route) {
  if (route.key) return String(route.key).toUpperCase();
  const base = route.entity ? pluralizeWords(route.entity) : pathWords(route.path);
  const key = base.join('_').toUpperCase();
  return key || 'ROUTE';
}

/**
 * (c) Idempotently append a route entry to src/app-routes.ts. The app uses a
 * named-key APP_ROUTES const object; we insert a new key just before the closing
 * `} as const;` of that object. Skips if a route with the same path already exists.
 */
export function appendRoute(srcDir, route, ctx, { context = 'app', access = 'protected' } = {}) {
  const routesPath = path.join(srcDir, 'app-routes.ts');
  if (!fs.existsSync(routesPath)) {
    ctx.warnings.push(`app-routes.ts not found at ${rel(routesPath)} — skipped route append for ${route.path}`);
    return;
  }
  let src = fs.readFileSync(routesPath, 'utf8');
  const routePath = route.path;
  // Idempotency: a route already declaring this exact path?
  if (new RegExp(`path:\\s*'${escapeRegex(routePath)}'`).test(src)) {
    skip(routesPath + ` (route ${routePath})`, ctx);
    return;
  }
  const key = routeKey(route);
  const entry = `\n\t// App data route — generated by scaffold-frontend.mjs.\n` +
    `\t${key}: {\n` +
    `\t\tpath: '${routePath}' as Route,\n` +
    `\t\tsearchParams: {},\n` +
    `\t\taccess: '${access}' as RouteAccessType,\n` +
    `\t\tcontext: '${context}' as SchemaContext,\n` +
    `\t},\n`;

  // Insert before the APP_ROUTES object's closing `} as const;`. Anchor on the
  // first `} as const;` AFTER `export const APP_ROUTES`.
  const anchorIdx = src.indexOf('export const APP_ROUTES');
  if (anchorIdx === -1) {
    ctx.warnings.push(`app-routes.ts has no \`export const APP_ROUTES\` — skipped route append for ${routePath}`);
    return;
  }
  const closeIdx = src.indexOf('} as const;', anchorIdx);
  if (closeIdx === -1) {
    ctx.warnings.push(`app-routes.ts APP_ROUTES has no \`} as const;\` close — skipped route append for ${routePath}`);
    return;
  }
  src = src.slice(0, closeIdx) + entry + src.slice(closeIdx);
  write(routesPath, src, ctx);
}

/**
 * (c) Idempotently append a NavItem to src/lib/navigation/sidebar-config.ts. We
 * insert into the `mainItems` array. Skips if an item with the same href exists.
 */
export function appendNavItem(srcDir, route, label, ctx) {
  const navPath = path.join(srcDir, 'lib', 'navigation', 'sidebar-config.ts');
  if (!fs.existsSync(navPath)) {
    ctx.warnings.push(`sidebar-config.ts not found at ${rel(navPath)} — skipped nav append for ${route.path}`);
    return;
  }
  let src = fs.readFileSync(navPath, 'utf8');
  const href = route.path;
  if (new RegExp(`href:\\s*'${escapeRegex(href)}'`).test(src)) {
    skip(navPath + ` (nav ${href})`, ctx);
    return;
  }
  const id = (route.entity ? words(route.entity) : pathWords(route.path)).join('-') || 'item';
  // Use a generic icon already imported by the base template (RiHome4Line) to
  // avoid adding an import the agent may not have; the agent swaps it for a
  // domain icon. (SEAM noted in the comment.)
  const item = `\t\t{\n` +
    `\t\t\tid: '${id}',\n` +
    `\t\t\tlabel: '${label}',\n` +
    `\t\t\ticon: RiHome4Line, // SEAM: swap for a domain icon from @remixicon/react\n` +
    `\t\t\thref: '${href}',\n` +
    `\t\t\tisActive: isRouteActive?.('${routeKey(route)}'),\n` +
    `\t\t},\n`;

  // Anchor: the `mainItems` array literal. Insert before its closing `];`.
  const miIdx = src.indexOf('mainItems');
  if (miIdx === -1) {
    ctx.warnings.push(`sidebar-config.ts has no \`mainItems\` array — skipped nav append for ${href} (add a NavItem by hand)`);
    return;
  }
  const openIdx = src.indexOf('[', miIdx);
  const closeIdx = src.indexOf('];', openIdx);
  if (openIdx === -1 || closeIdx === -1) {
    ctx.warnings.push(`sidebar-config.ts \`mainItems\` array not closed with \`];\` — skipped nav append for ${href}`);
    return;
  }
  // Drop the whitespace-only run that immediately precedes `];` (the close's own
  // indentation) so the new item lands at the array's item indent and the close
  // re-indents cleanly to one tab — regardless of the original close indentation.
  const head = src.slice(0, closeIdx).replace(/[ \t]*$/, '');
  src = head + item + '\t' + src.slice(closeIdx);
  write(navPath, src, ctx);
}
