/**
 * scripts/lib/scaffold-frontend/step-up.mjs — the StepUpProvider provider-ordering reconcile
 * (the b2b provider crash fix).
 *
 * wire-app.mjs writes src/components/blocks-providers.tsx at Phase 3, BEFORE `shadcn add`
 * installs the flow's blocks. When an installed block TRANSITIVELY pulls in use-step-up (e.g.
 * the org members/roles/invite/app-membership blocks call useStepUp() at render), the file
 * wire-app wrote does NOT wrap <StepUpProvider> — so useStepUp() throws at runtime. This
 * scaffolder runs at Phase 7 (AFTER the blocks are installed), so HERE we detect the installed
 * block and ensure the wrapper hands-free, byte-identically to wire-app's own reconcile.
 *
 *   stepUpBlockInstalled  the real "provider needed?" signal — the use-step-up block on disk
 *                         (the SAME signal wire-app uses), NOT `step-up ∈ brief.flows`.
 *   stepUpProvidersBody   the canonical blocks-providers.tsx body for a step-up-installed app
 *                         (kept BYTE-IDENTICAL to wire-app's providersBody so a later wire-app
 *                         run detects an in-sync wrapper and no-ops).
 *   ensureStepUpProvider  idempotent + contained reconcile (no-op when no use-step-up block —
 *                         so the owner canary / public-read blog stay byte-identical).
 */

import * as fs from 'fs';
import * as path from 'path';
import { write, skip, rel } from './writers.mjs';

/**
 * Whether the use-step-up / step-up-provider BLOCK is installed under the app — the
 * SAME signal wire-app.mjs uses to decide whether to wrap children in <StepUpProvider>
 * (blockFileExists(['auth','use-step-up','step-up-provider'])). The `shadcn add` on-ramp
 * installs use-step-up either because `step-up` is a chosen flow OR because another
 * installed block declares it as a DEPENDENCY — in BOTH cases StepUpProvider IS wired, so
 * a step-up-gated section has its provider. We therefore gate the step-up warning on the
 * ABSENCE of this block (the real wiring signal), not on `step-up ∈ brief.flows` (which
 * misses the dependency-install case → a false-negative warning). Tolerates the .tsx/.ts
 * extension the registry emits. Returns false pre-install (block dir not yet present).
 */
export function stepUpBlockInstalled(srcDir) {
  const base = path.join(srcDir, 'blocks', 'auth', 'use-step-up', 'step-up-provider');
  return fs.existsSync(base + '.tsx') || fs.existsSync(base + '.ts');
}

// The import specifiers for the two blocks the providers wrapper mounts — the SAME
// strings wire-app.mjs uses (RUNTIME_SPEC / STEPUP_SPEC), so the reconciled file below
// is byte-identical to what wire-app emits for a step-up-installed app.
const BLOCKS_RUNTIME_SPEC = '@/blocks/runtime/blocks-runtime';
const STEP_UP_PROVIDER_SPEC = '@/blocks/auth/use-step-up/step-up-provider';

/**
 * The canonical `blocks-providers.tsx` body for an app whose installed blocks include
 * use-step-up — i.e. wraps children in <StepUpProvider>. This string MUST stay
 * BYTE-IDENTICAL to wire-app.mjs's `providersBody` for the `stepUpInstalled === true`
 * case (see wire-app.mjs step (d)), so that after this reconcile a later `node
 * scripts/wire-app.mjs` run detects an in-sync wrapper and no-ops (its idempotency
 * guard matches /<StepUpProvider[\s>]/). If you change wire-app's providers body, change
 * this in lockstep. We reproduce it (rather than import wire-app) because wire-app is a
 * CLI with top-level side effects (arg parse / die / dynamic port allocation + run-state
 * write); importing it to reuse one string would re-run all of that.
 */
export function stepUpProvidersBody() {
  return `'use client';

import type { ReactNode } from 'react';
import { BlocksRuntime } from '${BLOCKS_RUNTIME_SPEC}';
import { StepUpProvider } from '${STEP_UP_PROVIDER_SPEC}';
import { TokenManager } from '@/lib/auth/token-manager';

// Owns the getToken closure on the client side, so layout.tsx (a Server Component) never passes
// a function across the server→client boundary (gotchas BLOCKS-009). BlocksRuntime owns the
// 'auth' + 'admin' namespaces (configures each + attaches Authorization per request via getToken);
// AppProvider still owns 'app'. StepUpProvider wraps children (the use-step-up block is installed).
// Generated by scripts/wire-app.mjs.
export function BlocksProviders({ children }: { children: ReactNode }) {
  return (
    <BlocksRuntime
      namespaces={['auth', 'admin']}
      getToken={() => TokenManager.getToken('admin').token?.accessToken}
    >
      <StepUpProvider>{children}</StepUpProvider>
    </BlocksRuntime>
  );
}
`;
}

/**
 * STEP-UP PROVIDER RECONCILE (the b2b provider-ordering fix). wire-app.mjs writes
 * src/components/blocks-providers.tsx at Phase 3, BEFORE `shadcn add` installs the flow's
 * blocks (Phase 5). So when an installed block TRANSITIVELY pulls in use-step-up (e.g. the
 * org members/roles/invite/app-membership blocks call useStepUp() at render), the file
 * wire-app wrote does NOT wrap <StepUpProvider> — and nothing re-wraps it after the block
 * lands, so useStepUp() throws at runtime and the org page crashes. scaffold-frontend runs
 * at Phase 7 (AFTER the blocks are installed), so HERE we can detect the installed block and
 * ensure the wrapper hands-free.
 *
 * Detection is by the INSTALLED block on disk (stepUpBlockInstalled — the SAME signal
 * wire-app uses), NOT by brief.flows: the crash-causing case has NO `step-up` flow and NO
 * step-up-gated account section — use-step-up arrives purely as a block DEPENDENCY of an org
 * block. Gating on flows would miss it. This is exactly wire-app's own reconcile semantics
 * (re-write when the desired StepUpProvider wrapping differs from what's on disk), mirrored
 * here as the documented fallback to invoking wire-app (whose other side effects — env writes,
 * dynamic port re-allocation + run-state rewrite — must not re-fire at Phase 7).
 *
 * Idempotent + contained:
 *   • No use-step-up block on disk → no-op (so a non-step-up app — the owner canary, the
 *     public-read blog — is NEVER given a StepUpProvider; blocks-providers.tsx stays byte-equal).
 *   • File missing → WARN (wire-app owns CREATING it at Phase 3); we never fabricate it here.
 *   • Already wraps <StepUpProvider> → skip (no change).
 *   • Has BlocksRuntime but no wrapper → re-write to the canonical step-up body (a full
 *     overwrite, exactly as wire-app's reconcile does).
 *   • No BlocksRuntime (unexpected shape) → WARN, leave untouched (never half-patch).
 */
export function ensureStepUpProvider(srcDir, ctx) {
  // GATE: only act when the use-step-up block is actually installed. This is the lone guard
  // that keeps the canary + blog byte-identical (they install no step-up-needing block).
  if (!stepUpBlockInstalled(srcDir)) return;

  const providersPath = path.join(srcDir, 'components', 'blocks-providers.tsx');
  if (!fs.existsSync(providersPath)) {
    ctx.warnings.push(
      `step-up provider reconcile: the use-step-up block is installed but ${rel(providersPath)} is missing — ` +
        'wire-app.mjs (Phase 3) creates the BlocksProviders wrapper; run it (node scripts/wire-app.mjs --app <app> --sub <db>) ' +
        'so the StepUpProvider wrap can be applied. An org/step-up block calls useStepUp() at render and will throw without it.',
    );
    return;
  }

  const existing = fs.readFileSync(providersPath, 'utf8');
  // Match the JSX WRAPPER tag, not any mention of the word (the no-step-up file's comment
  // literally says "StepUpProvider is omitted…", which a bare /StepUpProvider/ would
  // false-positive on — the regression wire-app's guard also avoids). Same regex as wire-app.
  if (/<StepUpProvider[\s>]/.test(existing)) {
    skip(providersPath + ' (StepUpProvider already wrapped)', ctx);
    return;
  }
  if (!/BlocksRuntime/.test(existing)) {
    ctx.warnings.push(
      `step-up provider reconcile: ${rel(providersPath)} has no BlocksRuntime wrapper (unexpected shape) — left untouched ` +
        '(never half-patch). Re-run wire-app.mjs to regenerate it, or wrap children in <StepUpProvider> by hand.',
    );
    return;
  }
  // Re-write to the canonical step-up-installed body (byte-identical to wire-app's), so the
  // installed org/step-up block's useStepUp() has its provider. Full overwrite mirrors
  // wire-app's reconcile. write() respects --dry-run (records, writes nothing in dry-run).
  write(providersPath, stepUpProvidersBody(), ctx);
}
